default:
  homepage:
    title: Xceptance - The Software Testing Experts 
    headline: Committed to Software Quality
    
de_DE:
  homepage:
    title: Xceptance - Qualitätssicherung von Software
    headline: Der Qualität von Software verpflichtet
   
