COMMENT:
  DESCRIPTION: This comment section is added for the show case only to explain how to use Neodymium Localization.
  RELATED SHOWCASE: NeodymiumLocalizationShowcase

default:
  homepage:
    title: Xceptance - The Software Testing Experts 
    headline: Committed to Software Quality
    subtitle: We help our clients optimize software testing and quality assurance
    
de:
  homepage:
    title: Xceptance - Qualitätssicherung von Software
    headline: Der Qualität von Software verpflichtet
   
de_AT:
  homepage:
    subtitle: Wir begleiten Sie auf Ihrem Weg zum besten Produkt.